TARGET_NAME="MGENetwork"
DERIVED_DATA_DIR=".derived_temp"
OUTPUT_DIR="docs"

# Save current branch.
CURRENT_BRANCH="echo $(git rev-parse --abbrev-ref HEAD)"

# Switch to the documentation branch.
git checkout gh-pages

# Generate doc for all the releases.
for tag in $(git tag);
do
  echo "⏳ Generating documentation for "$tag" release.";

  if [ -d "$OUTPUT_DIR/$tag" ]
  then
      echo "✅ Documentation for "$tag" already exists.";
  else
      git checkout "$tag";

      # Delete docs folder.
      echo "Removing old documentation."
      rm -rf docs

      # Generate documentation.
      echo "Generating documentation."
      xcodebuild docbuild \
        -scheme $TARGET_NAME \
        -derivedDataPath $DERIVED_DATA_DIR \
        -destination 'platform=iOS Simulator,name=iPhone 13' \
        OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path $OUTPUT_DIR/$tag --hosting-base-path swift-mge-network/"$tag"" \
        && echo "✅ Documentation generated for "$tag" release." \
        || echo "⚠️ Documentation skipped for "$tag".";

        # Delete derived data temporary dir.
        rm -rf $DERIVED_DATA_DIR

        # Commit generated documentation.
        git add docs
        git pull
        git commit -m "🤖💬 Autogenerated documentation."
        # git push origin gh-pages
    fi
done

# # Generating Static Hosting files.
# echo "Generating Static Hosting files."
# $(xcrun --find docc) process-archive \
#   transform-for-static-hosting $(echo $(find $DERIVED_DATA_DIR -type d -name 'MGENetwork.doccarchive')) \
#   --output-path $OUTPUT_DIR \
#   --hosting-base-path swift-mge-network

# Checkout previous branch.
echo "Returning on branch '$CURRENT_BRANCH'."
git checkout $CURRENT_BRANCH
