TARGET_NAME="MGENetwork"
DERIVED_DATA_DIR=".derived_temp"
OUTPUT_DIR="docs"


# Delete docs folder.
rm -rf docs

# Generate documentation.
xcodebuild docbuild \
  -scheme $TARGET_NAME \
  -derivedDataPath $DERIVED_DATA_DIR \
  -destination 'platform=iOS Simulator,name=iPhone 13'

$(xcrun --find docc) process-archive \
  transform-for-static-hosting $(echo $(find derived-temp -type d -name 'MGENetwork.doccarchive')) \
  --output-path $OUTPUT_DIR \
  --hosting-base-path swift-mge-network

# Delete derived data temporary dir.
rm -rf $DERIVED_DATA_DIR

# Commit generated documentation.
# git add docs
# git pull
# git commit -m "🤖💬 Autogenerated documentation."
