TARGET_NAME="MGENetwork"
DERIVED_DATA_DIR=".derived_temp"
OUTPUT_DIR="docs"


# Delete docs folder.
rm -rf docs

# Generate documentation.
xcodebuild docbuild \
  -scheme $TARGET_NAME \
  -derivedDataPath $DERIVED_DATA_DIR \
  -destination 'platform=iOS Simulator,name=iPhone 13'

# Generating Static Hosting files.
$(xcrun --find docc) process-archive \
  transform-for-static-hosting $(echo $(find $DERIVED_DATA_DIR -type d -name 'MGENetwork.doccarchive')) \
  --output-path $OUTPUT_DIR \
  --hosting-base-path swift-mge-network

# Delete derived data temporary dir.
rm -rf $DERIVED_DATA_DIR

# Save current branch.
CURRENT_BRANCH="echo $(git rev-parse --abbrev-ref HEAD)"

# Commit generated documentation on gh-pages branch.
git checkout gh-pages
git add docs
git pull
git commit -m "🤖💬 Autogenerated documentation."
git push

# Checkout previous branch.
git checkout $CURRENT_BRANCH
