{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCancelled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mgenetwork\/asynchronousoperation\/iscancelled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mgenetwork\/asynchronousoperation\/iscancelled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation\/isCancelled","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCancelled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isCancelled","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@MGENetwork@objc(cs)AsynchronousOperation(py)cancelled","modules":[{"name":"MGENetwork"}],"navigatorTitle":[{"kind":"identifier","text":"cancelled"}]},"hierarchy":{"paths":[["doc:\/\/MGENetwork\/documentation\/MGENetwork","doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation"]]},"references":{"doc://MGENetwork/documentation/MGENetwork":{"role":"collection","title":"MGENetwork","abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork","kind":"symbol","type":"topic","url":"\/documentation\/mgenetwork"},"doc://MGENetwork/documentation/MGENetwork/AsynchronousOperation":{"role":"symbol","title":"AsynchronousOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsynchronousOperation"}],"abstract":[{"type":"text","text":"A foundation for an operation implementing a KVO-monitored state."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AsynchronousOperation"}],"url":"\/documentation\/mgenetwork\/asynchronousoperation"},"doc://MGENetwork/documentation/MGENetwork/AsynchronousOperation/isCancelled":{"role":"symbol","title":"isCancelled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCancelled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation\/isCancelled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelled"}],"url":"\/documentation\/mgenetwork\/asynchronousoperation\/iscancelled"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cancelled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cancelled"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isCancelled"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"cancelled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1AsynchronousOperation\/title","value":"AsynchronousOperation"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1AsynchronousOperation\/fragments","value":[{"kind":"identifier","text":"AsynchronousOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1AsynchronousOperation~1isCancelled\/title","value":"cancelled"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1AsynchronousOperation~1isCancelled\/fragments","value":[{"kind":"identifier","text":"cancelled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}