{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"main"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mgenetwork\/asynchronousoperation\/main()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mgenetwork\/asynchronousoperation\/main()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation\/main()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"main"},{"kind":"text","text":"()"}],"title":"main()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@MGENetwork@objc(cs)AsynchronousOperation(im)main","modules":[{"name":"MGENetwork"}],"navigatorTitle":[{"kind":"identifier","text":"main"}]},"hierarchy":{"paths":[["doc:\/\/MGENetwork\/documentation\/MGENetwork","doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation"]]},"references":{"doc://MGENetwork/documentation/MGENetwork":{"role":"collection","title":"MGENetwork","abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork","kind":"symbol","type":"topic","url":"\/documentation\/mgenetwork"},"doc://MGENetwork/documentation/MGENetwork/AsynchronousOperation/main()":{"role":"symbol","title":"main()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"main"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation\/main()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"main"}],"url":"\/documentation\/mgenetwork\/asynchronousoperation\/main()"},"doc://MGENetwork/documentation/MGENetwork/AsynchronousOperation":{"role":"symbol","title":"AsynchronousOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsynchronousOperation"}],"abstract":[{"type":"text","text":"A foundation for an operation implementing a KVO-monitored state."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AsynchronousOperation"}],"url":"\/documentation\/mgenetwork\/asynchronousoperation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"main"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"main"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"main"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1AsynchronousOperation~1main()\/title","value":"main"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1AsynchronousOperation~1main()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"main"}]},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1AsynchronousOperation\/title","value":"AsynchronousOperation"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1AsynchronousOperation\/fragments","value":[{"kind":"identifier","text":"AsynchronousOperation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}