{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockURLProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mgenetwork\/mockurlprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mgenetwork\/mockurlprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/MGENetwork\/objc(cs)NSURLProtocol"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/MGENetwork\/objc(pl)NSObject","doc:\/\/MGENetwork\/s7CVarArgP","doc:\/\/MGENetwork\/s28CustomDebugStringConvertibleP","doc:\/\/MGENetwork\/s23CustomStringConvertibleP","doc:\/\/MGENetwork\/SQ","doc:\/\/MGENetwork\/SH","doc:\/\/MGENetwork\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Collects all the mock responses from the network."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockURLProtocol"}],"title":"MockURLProtocol","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@MGENetwork@objc(cs)MockURLProtocol","modules":[{"name":"MGENetwork"}],"navigatorTitle":[{"kind":"identifier","text":"MockURLProtocol"}]},"hierarchy":{"paths":[["doc:\/\/MGENetwork\/documentation\/MGENetwork"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/startLoading()","doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/stopLoading()"]},{"title":"Type Properties","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/shouldCheckQueryParameters"]},{"title":"Type Methods","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/add(requests:)","doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/canInit(with:)","doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/canonicalRequest(for:)"]},{"title":"Enumerations","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/MockNetworkRequestError"]}],"references":{"doc://MGENetwork/documentation/MGENetwork/MockURLProtocol/add(requests:)":{"role":"symbol","title":"add(requests:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requests"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"MockNetworkExchange","preciseIdentifier":"s:10MGENetwork19MockNetworkExchangeV"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"Adds the given set of requests to the mockable requests."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/add(requests:)","kind":"symbol","type":"topic","url":"\/documentation\/mgenetwork\/mockurlprotocol\/add(requests:)"},"doc://MGENetwork/documentation/MGENetwork/MockURLProtocol/stopLoading()":{"role":"symbol","title":"stopLoading()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLoading"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/stopLoading()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopLoading"}],"url":"\/documentation\/mgenetwork\/mockurlprotocol\/stoploading()"},"doc://MGENetwork/documentation/MGENetwork/MockURLProtocol":{"role":"symbol","title":"MockURLProtocol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockURLProtocol"}],"abstract":[{"type":"text","text":"Collects all the mock responses from the network."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockURLProtocol"}],"url":"\/documentation\/mgenetwork\/mockurlprotocol"},"doc://MGENetwork/documentation/MGENetwork/MockURLProtocol/startLoading()":{"role":"symbol","title":"startLoading()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLoading"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/startLoading()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startLoading"}],"url":"\/documentation\/mgenetwork\/mockurlprotocol\/startloading()"},"doc://MGENetwork/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/MGENetwork\/SQ"},"doc://MGENetwork/objc(cs)NSURLProtocol":{"type":"unresolvable","title":"NSURLProtocol","identifier":"doc:\/\/MGENetwork\/objc(cs)NSURLProtocol"},"doc://MGENetwork/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/MGENetwork\/objc(pl)NSObject"},"doc://MGENetwork/documentation/MGENetwork":{"role":"collection","title":"MGENetwork","abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork","kind":"symbol","type":"topic","url":"\/documentation\/mgenetwork"},"doc://MGENetwork/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/MGENetwork\/s8SendableP"},"doc://MGENetwork/documentation/MGENetwork/MockURLProtocol/initWithRequest:cachedResponse:client:":{"role":"symbol","title":"initWithRequest:cachedResponse:client:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequest:cachedResponse:client:"}],"abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/initWithRequest:cachedResponse:client:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRequest:cachedResponse:client:"}],"url":"\/documentation\/mgenetwork\/mockurlprotocol\/initwithrequest:cachedresponse:client:"},"doc://MGENetwork/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/MGENetwork\/s23CustomStringConvertibleP"},"doc://MGENetwork/documentation/MGENetwork/MockURLProtocol/canInit(with:)":{"role":"symbol","title":"canInit(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canInit"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/canInit(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canInitWithRequest:"}],"url":"\/documentation\/mgenetwork\/mockurlprotocol\/caninit(with:)"},"doc://MGENetwork/documentation/MGENetwork/MockURLProtocol/shouldCheckQueryParameters":{"role":"symbol","title":"shouldCheckQueryParameters","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldCheckQueryParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not query parameters must be checked when distinguish between two responses."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/shouldCheckQueryParameters","kind":"symbol","type":"topic","url":"\/documentation\/mgenetwork\/mockurlprotocol\/shouldcheckqueryparameters"},"doc://MGENetwork/documentation/MGENetwork/MockURLProtocol/canonicalRequest(for:)":{"role":"symbol","title":"canonicalRequest(for:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canonicalRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"}],"abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/canonicalRequest(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canonicalRequestForRequest:"}],"url":"\/documentation\/mgenetwork\/mockurlprotocol\/canonicalrequest(for:)"},"doc://MGENetwork/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/MGENetwork\/s7CVarArgP"},"doc://MGENetwork/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/MGENetwork\/s28CustomDebugStringConvertibleP"},"doc://MGENetwork/documentation/MGENetwork/MockURLProtocol/MockNetworkRequestError":{"role":"symbol","title":"MockURLProtocol.MockNetworkRequestError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockNetworkRequestError"}],"abstract":[{"type":"text","text":"The errors that may occur with the mocked network requests."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/MockNetworkRequestError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockNetworkRequestError"}],"url":"\/documentation\/mgenetwork\/mockurlprotocol\/mocknetworkrequesterror"},"doc://MGENetwork/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/MGENetwork\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MockURLProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MockURLProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MockURLProtocol"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/initWithRequest:cachedResponse:client:","doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/startLoading()","doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/stopLoading()"]},{"title":"Type Methods","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/canInit(with:)","doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol\/canonicalRequest(for:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockURLProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSURLProtocol","preciseIdentifier":"c:objc(cs)NSURLProtocol"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol~1stopLoading()\/title","value":"stopLoading"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol~1stopLoading()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol\/title","value":"MockURLProtocol"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol\/fragments","value":[{"kind":"identifier","text":"MockURLProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol~1startLoading()\/title","value":"startLoading"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol~1startLoading()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol~1canInit(with:)\/title","value":"canInitWithRequest:"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol~1canInit(with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"canInitWithRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol~1canonicalRequest(for:)\/title","value":"canonicalRequestForRequest:"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol~1canonicalRequest(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"canonicalRequestForRequest:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}