{"variants":[{"paths":["\/documentation\/mgenetwork"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mgenetwork"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/MGENetwork\/documentation\/MGENetwork","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation","doc:\/\/MGENetwork\/documentation\/MGENetwork\/CompletionOperation","doc:\/\/MGENetwork\/documentation\/MGENetwork\/DataTaskOperation","doc:\/\/MGENetwork\/documentation\/MGENetwork\/DownloadOperation","doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol","doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkClient"]},{"title":"Protocols","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/Endpoint","doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkClientConfiguration","doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkOperation","doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkProvider","doc:\/\/MGENetwork\/documentation\/MGENetwork\/OperationExecutor","doc:\/\/MGENetwork\/documentation\/MGENetwork\/ParametersEncoder","doc:\/\/MGENetwork\/documentation\/MGENetwork\/Requestable"]},{"title":"Structures","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockNetworkExchange","doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockResponse","doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkLoggerConfiguration","doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkRequest"]},{"title":"Type Aliases","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/Completion","doc:\/\/MGENetwork\/documentation\/MGENetwork\/HTTPHeaders","doc:\/\/MGENetwork\/documentation\/MGENetwork\/Path"]},{"title":"Enumerations","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/HTTPMethod","doc:\/\/MGENetwork\/documentation\/MGENetwork\/HTTPParametersEncoder","doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkError","doc:\/\/MGENetwork\/documentation\/MGENetwork\/Parameters"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"MGENetwork","title":"MGENetwork","symbolKind":"module","role":"collection","modules":[{"name":"MGENetwork"}]},"hierarchy":{"paths":[[]]},"references":{"doc://MGENetwork/documentation/MGENetwork/HTTPMethod":{"role":"symbol","title":"HTTPMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPMethod"}],"abstract":[{"type":"text","text":"The set of HTTP methods for an HTTP request."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/HTTPMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPMethod"}],"url":"\/documentation\/mgenetwork\/httpmethod"},"doc://MGENetwork/documentation/MGENetwork/MockResponse":{"role":"symbol","title":"MockResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockResponse"}],"abstract":[{"type":"text","text":"A mocked response, used while writing unit tests."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockResponse"}],"url":"\/documentation\/mgenetwork\/mockresponse"},"doc://MGENetwork/documentation/MGENetwork/NetworkLoggerConfiguration":{"role":"symbol","title":"NetworkLoggerConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkLoggerConfiguration"}],"abstract":[{"type":"text","text":"The configuration for the "},{"type":"codeVoice","code":"NetworkClient"},{"type":"text","text":" logger."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkLoggerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkLoggerConfiguration"}],"url":"\/documentation\/mgenetwork\/networkloggerconfiguration"},"doc://MGENetwork/documentation/MGENetwork/Path":{"role":"symbol","title":"Path","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Path"}],"abstract":[{"type":"text","text":"Represents the path of an URL string."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/Path","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Path"}],"url":"\/documentation\/mgenetwork\/path"},"doc://MGENetwork/documentation/MGENetwork/AsynchronousOperation":{"role":"symbol","title":"AsynchronousOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AsynchronousOperation"}],"abstract":[{"type":"text","text":"A foundation for an operation implementing a KVO-monitored state."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AsynchronousOperation"}],"url":"\/documentation\/mgenetwork\/asynchronousoperation"},"doc://MGENetwork/documentation/MGENetwork/Endpoint":{"role":"symbol","title":"Endpoint","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Endpoint"}],"abstract":[{"type":"text","text":"An endpoint provider."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/Endpoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Endpoint"}],"url":"\/documentation\/mgenetwork\/endpoint"},"doc://MGENetwork/documentation/MGENetwork/CompletionOperation":{"role":"symbol","title":"CompletionOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletionOperation"}],"abstract":[{"type":"text","text":"An operation that executes a completion upon its termination."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/CompletionOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompletionOperation"}],"url":"\/documentation\/mgenetwork\/completionoperation"},"doc://MGENetwork/documentation/MGENetwork/Completion":{"role":"symbol","title":"Completion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Completion"}],"abstract":[{"type":"text","text":"A completion to handle a result or an error."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/Completion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Completion"}],"url":"\/documentation\/mgenetwork\/completion"},"doc://MGENetwork/documentation/MGENetwork/Parameters":{"role":"symbol","title":"Parameters","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Parameters"}],"abstract":[{"type":"text","text":"Parameters for a "},{"type":"codeVoice","code":"NetworkRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/Parameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Parameters"}],"url":"\/documentation\/mgenetwork\/parameters"},"doc://MGENetwork/documentation/MGENetwork/MockURLProtocol":{"role":"symbol","title":"MockURLProtocol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockURLProtocol"}],"abstract":[{"type":"text","text":"Collects all the mock responses from the network."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockURLProtocol"}],"url":"\/documentation\/mgenetwork\/mockurlprotocol"},"doc://MGENetwork/documentation/MGENetwork":{"role":"collection","title":"MGENetwork","abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork","kind":"symbol","type":"topic","url":"\/documentation\/mgenetwork"},"doc://MGENetwork/documentation/MGENetwork/ParametersEncoder":{"role":"symbol","title":"ParametersEncoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParametersEncoder"}],"abstract":[{"type":"text","text":"An encoder of "},{"type":"codeVoice","code":"Parameters"},{"type":"text","text":"."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/ParametersEncoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ParametersEncoder"}],"url":"\/documentation\/mgenetwork\/parametersencoder"},"doc://MGENetwork/documentation/MGENetwork/HTTPParametersEncoder":{"role":"symbol","title":"HTTPParametersEncoder","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPParametersEncoder"}],"abstract":[{"type":"text","text":"Encodes query and body parameters for an HTTP request."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/HTTPParametersEncoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPParametersEncoder"}],"url":"\/documentation\/mgenetwork\/httpparametersencoder"},"doc://MGENetwork/documentation/MGENetwork/NetworkError":{"role":"symbol","title":"NetworkError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkError"}],"abstract":[{"type":"text","text":"Error occurring upon network tasks."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkError"}],"url":"\/documentation\/mgenetwork\/networkerror"},"doc://MGENetwork/documentation/MGENetwork/NetworkRequest":{"role":"symbol","title":"NetworkRequest","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkRequest"}],"abstract":[{"type":"text","text":"Models a network request generic over the response type."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkRequest"}],"url":"\/documentation\/mgenetwork\/networkrequest"},"doc://MGENetwork/documentation/MGENetwork/NetworkProvider":{"role":"symbol","title":"NetworkProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkProvider"}],"abstract":[{"type":"text","text":"An entity providing ways of making requests against the network."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkProvider"}],"url":"\/documentation\/mgenetwork\/networkprovider"},"doc://MGENetwork/documentation/MGENetwork/NetworkClient":{"role":"symbol","title":"NetworkClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkClient"}],"abstract":[{"type":"text","text":"A client for making network calls."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkClient"}],"url":"\/documentation\/mgenetwork\/networkclient"},"doc://MGENetwork/documentation/MGENetwork/MockNetworkExchange":{"role":"symbol","title":"MockNetworkExchange","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockNetworkExchange"}],"abstract":[{"type":"text","text":"Associates an "},{"type":"codeVoice","code":"URLRequest"},{"type":"text","text":" to a "},{"type":"codeVoice","code":"MockResponse"},{"type":"text","text":"."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockNetworkExchange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MockNetworkExchange"}],"url":"\/documentation\/mgenetwork\/mocknetworkexchange"},"doc://MGENetwork/documentation/MGENetwork/NetworkOperation":{"role":"symbol","title":"NetworkOperation","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkOperation"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"Operation"},{"type":"text","text":" performing network tasks."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkOperation"}],"url":"\/documentation\/mgenetwork\/networkoperation"},"doc://MGENetwork/documentation/MGENetwork/Requestable":{"role":"symbol","title":"Requestable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Requestable"}],"abstract":[{"type":"text","text":"An entity that can be used to describe an HTTP request."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/Requestable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Requestable"}],"url":"\/documentation\/mgenetwork\/requestable"},"doc://MGENetwork/documentation/MGENetwork/HTTPHeaders":{"role":"symbol","title":"HTTPHeaders","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTPHeaders"}],"abstract":[{"type":"text","text":"A type for representing HTTP header fields."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/HTTPHeaders","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HTTPHeaders"}],"url":"\/documentation\/mgenetwork\/httpheaders"},"doc://MGENetwork/documentation/MGENetwork/OperationExecutor":{"role":"symbol","title":"OperationExecutor","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"OperationExecutor"}],"abstract":[{"type":"text","text":"An entity that can execute an "},{"type":"codeVoice","code":"Operation"},{"type":"text","text":"."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/OperationExecutor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OperationExecutor"}],"url":"\/documentation\/mgenetwork\/operationexecutor"},"doc://MGENetwork/documentation/MGENetwork/NetworkClientConfiguration":{"role":"symbol","title":"NetworkClientConfiguration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkClientConfiguration"}],"abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkClientConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkClientConfiguration"}],"url":"\/documentation\/mgenetwork\/networkclientconfiguration"},"doc://MGENetwork/documentation/MGENetwork/DataTaskOperation":{"role":"symbol","title":"DataTaskOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataTaskOperation"}],"abstract":[{"type":"text","text":"An operation for network calls, using data tasks generated from the given session."},{"type":"text","text":" "},{"type":"text","text":"Performs a "},{"type":"codeVoice","code":"NetworkRequest"},{"type":"text","text":" a completion upon its task termination."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/DataTaskOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DataTaskOperation"}],"url":"\/documentation\/mgenetwork\/datataskoperation"},"doc://MGENetwork/documentation/MGENetwork/DownloadOperation":{"role":"symbol","title":"DownloadOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DownloadOperation"}],"abstract":[{"type":"text","text":"Operation for download related tasks."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/DownloadOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DownloadOperation"}],"url":"\/documentation\/mgenetwork\/downloadoperation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/MGENetwork\/documentation\/MGENetwork\/AsynchronousOperation","doc:\/\/MGENetwork\/documentation\/MGENetwork\/MockURLProtocol"]}]},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1AsynchronousOperation\/title","value":"AsynchronousOperation"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1AsynchronousOperation\/fragments","value":[{"kind":"identifier","text":"AsynchronousOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol\/title","value":"MockURLProtocol"},{"op":"replace","path":"\/references\/doc:~1~1MGENetwork~1documentation~1MGENetwork~1MockURLProtocol\/fragments","value":[{"kind":"identifier","text":"MockURLProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}