name: CI

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clean
      run: swift package clean

    - name: iOS Tests
      run: xcodebuild test -scheme MGENetwork -destination "platform=iOS Simulator,OS=latest,name=iPhone 12"
