name: Build & Test

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
      - '*'

jobs:
  build:
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clean
      run: swift package clean
    - name: Build for MacOS
      run: swift build -v
    - name: Build for iOS
      run: swift build -v -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
    - name: Run MacOS tests
      run: swift test -v
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme IndexedDataStore -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
