# Build and deploy DocC to GitHub pages. Based off of @pointfree's work here:
# https://github.com/pointfreeco/swift-MGENetwork/blob/main/.github/workflows/documentation.yml
name: Documentation

on:
  release:
    types:
      - published
  push:
    branches:
      - feature/add-documentation

jobs:
  build:
    runs-on: macos-12

    env:
      TARGET_NAME: MGENetwork
      OUTPUT_DIR: docs-out

    steps:
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ${{ env.OUTPUT_DIR }}

      - name: Print Swift Version
        run: xcrun swift -version

      - name: Force Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app && /usr/bin/xcodebuild -version

      - name: Resolve Swift Package dependencies
        run: swift package resolve

      - name: Generate documentation for every package version
        run: |
          rm -rf ${{ env.OUTPUT_DIR }}/.git;
          rm -rf ${{ env.OUTPUT_DIR }}/master;

          for tag in $(echo "master"; git tag);
          do
            echo "⏳ Generating documentation for "$tag" release.";

            if [ -d "${{ env.OUTPUT_DIR }}/$tag" ]
            then
              echo "✅ Documentation for "$tag" already exists.";
            else
              git checkout "$tag";

              xcodebuild docbuild \
                -scheme ${{ env.TARGET_NAME }} \
                -destination 'generic/platform=iOS' \
                -derivedDataPath .derivedData \
                OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path ${{ env.OUTPUT_DIR }}/$tag --hosting-base-path ${{ github.event.repository.name }}/"$tag"

              mkdir "${{ env.OUTPUT_DIR }}/$tag"

              find .derivedData \
                -name "${{ env.TARGET_NAME }}.doccarchive" \
                -exec cp -R {} ${{ env.OUTPUT_DIR }}/$tag \;

            fi;

          done

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: ${{ env.OUTPUT_DIR }}
          single-commit: true
