name: Publish Documentation on Github Pages

on:
  release:
    types:
      - published
  push:
    branches:
      - feature/add-documentation

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Resolve package dependencies
      run: swift package resolve

    - name: Build documentation
      run: |
        xcodebuild docbuild \
          -scheme MGENetwork \
          -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" \
          -derivedDataPath derived-temp

    - name: Setting local environment
      run: |
        echo "DOC_ARCHIVE_PATH=$(echo $(find derived-temp -type d -name 'MGENetwork.doccarchive'))" >> $GITHUB_ENV

    - name: Generate static hosting files
      run: |
        $(xcrun --find docc) process-archive \
          transform-for-static-hosting ${{ env.DOC_ARCHIVE_PATH }} \
          --output-path docs \
          --hosting-base-path /swift-mge-network/

    - name: Publish documentation to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: docs
        single-commit: true
