# Build and deploy DocC to GitHub pages. Based off of @pointfree's work here:
# https://github.com/pointfreeco/swift-MGENetwork/blob/main/.github/workflows/documentation.yml
name: Documentation

on:
  release:
    types:
      - published
  push:
    branches:
      - feature/add-documentation

env:
  TARGET_NAME: MGENetwork
  DERIVED_DATA_DIR: .derived_temp
  OUTPUT_DIR: docs-out

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout Package
        uses: actions/checkout@v2

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs-out

      - name: Build documentation
        run: >
          for tag in $(git tag);
          do
            echo "⏳ Generating documentation for "$tag" release.";

            if [ -d "$OUTPUT_DIR/$tag" ]
            then
                echo "✅ Documentation for "$tag" already exists.";
            else
                git checkout "$tag";

                xcodebuild docbuild \
                  -scheme $TARGET_NAME \
                  -derivedDataPath $DERIVED_DATA_DIR \
                  -destination 'platform=iOS Simulator,name=iPhone 13' \
                  OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path $OUTPUT_DIR/$tag --hosting-base-path swift-mge-network/"$tag"" \
                  && echo "✅ Documentation generated for "$tag" release." \
                  || echo "⚠️ Documentation skipped for "$tag".";
            fi;
          done

      - name: Temp step
        run: echo $(ls $OUTPUT_DIR);

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs-out
          single-commit: true
