# Build and deploy DocC to GitHub pages. Based off of @pointfree's work here:
# https://github.com/pointfreeco/swift-MGENetwork/blob/main/.github/workflows/documentation.yml
name: Documentation

on:
  release:
    types:
      - published
  push:
    branches:
      - feature/add-documentation

jobs:
  build:
    runs-on: macos-12

    env:
      TARGET_NAME: MGENetwork
      OUTPUT_DIR: docs

    steps:
      - name: Checkout Package
        uses: actions/checkout@v2

      - name: Build documentation
        run: |
          swift package --allow-writing-to-directory ${{ env.OUTPUT_DIR }} \
            generate-documentation --target ${{ env.TARGET_NAME }} \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path ${{ github.event.repository.name }} \
            --output-path ${{ env.OUTPUT_DIR }}

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs

      - name: Commit changes on gh-pages branch
        run: |
          git add docs
          git pull
          git commit -m "🤖💬 Autogenerated documentation."
          git push origin gh-pages

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs
          single-commit: true
