# Build and deploy DocC to GitHub pages. Based off of @pointfree's work here:
# https://github.com/pointfreeco/swift-MGENetwork/blob/main/.github/workflows/documentation.yml
name: Documentation

on:
  release:
    types:
      - published
  push:
    branches:
      - feature/add-documentation

jobs:
  build:
    runs-on: macos-12

    env:
      TARGET_NAME: MGENetwork
      OUTPUT_DIR: docs-out

    steps:
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ${{ env.OUTPUT_DIR }}

      - name: Force Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app && /usr/bin/xcodebuild -version

      - name: Resolve Swift Package dependencies
        run: swift package resolve

      - name: Generate documentation for every package version
        run: |
          rm -rf ${{ env.OUTPUT_DIR }}/.git;
          rm -rf ${{ env.OUTPUT_DIR }}/master;

          for tag in $(echo "master"; git tag);
          do
            echo "⏳ Generating documentation for "$tag" release.";

            if [ -d "${{ env.OUTPUT_DIR }}/$tag" ]
            then
              echo "✅ Documentation for "$tag" already exists.";
            else
              git checkout "$tag";
              mkdir -p Sources/Parsing/Documentation.docc;
              rm -rf .build/symbol-graphs;
              mkdir -p .build/symbol-graphs;

              swift build -v -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator" --target ${{ env.TARGET_NAME }} \
                && swift-docc/.build/release/docc convert Sources/Parsing/Documentation.docc \
                  --fallback-display-name ${{ env.TARGET_NAME }} \
                  --fallback-bundle-identifier com.mge.MGENetwork \
                  --fallback-bundle-version 0.0.0 \
                  --transform-for-static-hosting \
                  --hosting-base-path /swift-mge-network/"$tag" \
                  --output-path ${{ env.OUTPUT_DIR }}/"$tag" \
                  && echo "✅ Documentation generated for "$tag" release." \
                  || echo "⚠️ Documentation skipped for "$tag".";
            fi;
          done

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: ${{ env.OUTPUT_DIR }}
          single-commit: true
