name: Publish Documentation - Jazzy

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
      - '*'

jobs: 
    
    publish:
    runs-on: macos-latest
    steps:
      – uses: actions/checkout@v2
      – name: Publish Jazzy Docs
  
    uses: sersoft-gmbh/swifty-docs-action@v1
    with:
      output: docs
      clean: true