name: Build & Test

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
      - '*'

jobs:
  build:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Clean
      run: swift package clean
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
